### ISSUE TITLE
Error running example provided

### ISSUE THREAD

**Issue by r0hitsharma** [robertstettner/elasticsearch-csv#1]
I get the following error:

```
Unhandled rejection Error: Not Found
    at respond (/home/r0hit/Code/elasticsearch-csv-import/node_modules/elasticsearch-csv/node_modules/elasticsearch/src/lib/transport.js:232:15)
    at checkRespForFailure (/home/r0hit/Code/elasticsearch-csv-import/node_modules/elasticsearch-csv/node_modules/elasticsearch/src/lib/transport.js:200:7)
    at HttpConnector.<anonymous> (/home/r0hit/Code/elasticsearch-csv-import/node_modules/elasticsearch-csv/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/home/r0hit/Code/elasticsearch-csv-import/node_modules/elasticsearch-csv/node_modules/lodash/index.js:3095:19)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

I have exactly the sample code setup, only changes being index, type, host and filePath. I have tried with a few different csv files in different formats, all exactly producing the same error. The files are sized between 1.3-1.8 MB.

**Comment by robertstettner** [comment]
Hi there @r0hitsharma,

Sorry for not getting to you sooner. Could you please provide me with the code/options you are passing, so that I can see what is going on?

**Comment by robertstettner** [comment]
Sorry closing this one. If you still have a problem, create a new issue.
